
title: Ciemna strona
email: bob-adook@tutanota.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog o ochronie prywatności i przekrętach korporacji.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ciemnastrona.com.pl" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Bob-A-Dook

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

collections:
  serie:
    output: true
  tutorials:
    output: true


#emoji:
#  src: "/assets/images/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
